name: nextjs - Build and Push Docker Image

on:
  push:
  create:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create .env file
        run: |
          curl -H "Authorization: Bearer ${{ secrets.NEXTJS_INUVA_DEPLOY_TOKEN }}" \
               -o .env \
               https://laurens.inuva.me:3000/api/projects/6/env

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/laurens-mesure/nextjs:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Notify Inuva Deploy
        run: |
          curl -X POST \
               -H "Authorization: Bearer ${{ secrets.NEXTJS_INUVA_DEPLOY_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{"username":"${{ github.actor }}","password":"${{ secrets.GITHUB_TOKEN }}","sha":"${{ github.sha }}","ref":"${{ github.ref_name }}"}' \
               --max-time 120 \
               https://laurens.inuva.me:3000/api/projects/6/update
